name: pomato
description: "A free and open source Pomodoro timer app for Android, made using Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.3
  flutter_settings_ui: ^3.0.0
  sleek_circular_slider: ^2.0.1
  provider: ^6.1.2
  flutter_form_builder: ^9.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
